env:
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: namikazze/ubuntu:22.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "IQ-7"
       - git config --global user.email "iq7.dev@gmail.com"
       - echo "$CREDENTIALS" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p /tmp/ccache
       - rclone copy rom:aex/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/AospExtended/manifest -b 10.x -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/IQ-7/device_xiaomi_whyred -b aex-10 device/xiaomi/whyred
      - git clone --depth=1 https://github.com/IQ-7/device_xiaomi_sdm660-common -b aex device/xiaomi/sdm660-common
      - git clone --depth=1 https://github.com/IQ-7/vendor_xiaomi_whyred -b 10 vendor/xiaomi/whyred
      - git clone --depth=1 https://github.com/IQ-7/vendor_xiaomi_sdm660-common -b 10 vendor/xiaomi/sdm660-common
#      - git clone --depth=1 https://github.com/IQ-7/device_xiaomi_whyred -b 10.x device/xiaomi/whyred
#      - git clone --depth=1 https://github.com/IQ-7/device_xiaomi_sdm660-common -b 10.x device/xiaomi/sdm660-common
#      - git clone --depth=1 https://github.com/IQ-7/vendor_xiaomi --single-branch -b 10.x vendor/xiaomi  
      - git clone --depth=1 https://github.com/IQ-7/android_kernel_xiaomi_whyred --single-branch -b aex-10 kernel/xiaomi/whyred
      - git clone --depth=1 https://github.com/ifeincarnation/vendor_MiuiCamera --single-branch -b 10 vendor/MiuiCamera
      - git clone --depth=1 https://github.com/ifeincarnation/vendor_dirac --single-branch -b 10 vendor/dirac
      # Source
      - rm -rf vendor/aosp
      - git clone --depth=1 https://github.com/IQ-7/platform_vendor_aosp -b 10.x vendor/aosp
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/whyred/ && ls AospExtended*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/whyred/ && ls AospExtended*.zip)"
      - rclone copy /tmp/rom/out/target/product/whyred/AospExtended*.zip rom:whyred -P
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/whyred/ && ls AospExtended*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Download link https://rom.builderz.workers.dev/0:/whyred/$(cd /tmp/rom/out/target/product/whyred/ && ls AospExtended*.zip)"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz rom:aex -P
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
